#!/usr/bin/env python3
# Copyright 2026 Ego Hygiene
# SPDX-License-Identifier: MIT

"""Validate the issue #43 risk register and render its manuscript table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER_PATH = Path("paper/tables/risk-mitigation-status.json")
OUTPUT_PATH = Path("paper/tables/risk-mitigation-status.tex")

EXPECTED_RISK_IDS = (
    "ANT-RISK-001",
    "ANT-RISK-002",
    "ANT-RISK-003",
    "ANT-RISK-004",
    "ANT-RISK-005",
    "ANT-RISK-006",
    "ANT-RISK-007",
)
STATUS_LABELS = {
    "mixed": "Mixed",
    "specified": "Specified",
    "unresolved": "Unresolved",
    "blocked": "Blocked",
}
REQUIRED_ROW_FIELDS = (
    "id",
    "title",
    "evidence_layer",
    "status",
    "current_control",
    "residual_risk",
    "owner",
    "blocking_gate",
)


def load_register(project: Path = ROOT) -> dict:
    """Load the canonical, machine-readable risk register."""
    return json.loads((project / REGISTER_PATH).read_text(encoding="utf-8"))


def validate_register(register: dict) -> list[str]:
    """Return every governance error without interpreting controls as evidence."""
    errors: list[str] = []
    if register.get("schema") != "antidote.risk-register/v1":
        errors.append("unexpected risk-register schema")
    if register.get("version") != "1.0.0":
        errors.append("risk-register version must be 1.0.0")
    if register.get("status") != "design-audit":
        errors.append("risk-register status must remain design-audit")
    if register.get("owned_by") != "egohygiene/antidote#43":
        errors.append("risk-register ownership must remain issue #43")
    if register.get("formal_collection_authorized") is not False:
        errors.append("risk register must not authorize formal collection")
    boundary = register.get("boundary")
    if not isinstance(boundary, str) or "does not establish" not in boundary:
        errors.append("risk-register boundary must state what it does not establish")

    definitions = register.get("status_definitions")
    if not isinstance(definitions, dict) or set(definitions) != set(STATUS_LABELS):
        errors.append("risk-register status definitions drifted")
    elif any(not isinstance(value, str) or not value for value in definitions.values()):
        errors.append("risk-register status definitions must be non-empty")

    risks = register.get("risks")
    if not isinstance(risks, list):
        return errors + ["risk register must contain a risks array"]
    identifiers = [risk.get("id") for risk in risks if isinstance(risk, dict)]
    if tuple(identifiers) != EXPECTED_RISK_IDS:
        errors.append("risk-register roster or order drifted")

    statuses: set[str] = set()
    for index, risk in enumerate(risks):
        if not isinstance(risk, dict):
            errors.append(f"risk row {index} must be an object")
            continue
        risk_id = str(risk.get("id", f"row-{index}"))
        for field in REQUIRED_ROW_FIELDS:
            value = risk.get(field)
            if not isinstance(value, str) or not value.strip():
                errors.append(f"{risk_id} requires non-empty {field}")
        status = risk.get("status")
        if status not in STATUS_LABELS:
            errors.append(f"{risk_id} has invalid status: {status}")
        else:
            statuses.add(status)
        if risk.get("residual_risk") == risk.get("current_control"):
            errors.append(f"{risk_id} collapses control and residual risk")
        if "none" == str(risk.get("blocking_gate", "")).strip().casefold():
            errors.append(f"{risk_id} cannot omit its blocking gate")

    if statuses != set(STATUS_LABELS):
        errors.append("risk register must preserve mixed, specified, unresolved, and blocked rows")
    return errors


def tex_escape(value: str) -> str:
    """Escape plain register text for a LaTeX table cell."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def render_table(register: dict) -> str:
    """Return the deterministic compact LaTeX projection."""
    errors = validate_register(register)
    if errors:
        raise ValueError("; ".join(errors))

    lines = [
        "% Generated by scripts/generate_risk_table.py.",
        "% Source: paper/tables/risk-mitigation-status.json.",
        "% Do not edit this projection by hand.",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.4pt}%",
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.19\linewidth}"
        r">{\raggedright\arraybackslash}p{0.31\linewidth}"
        r">{\raggedright\arraybackslash}p{0.34\linewidth}"
        r">{\raggedright\arraybackslash}p{0.10\linewidth}@{}}",
        r"\toprule",
        r"Risk / layer & Current control & Residual risk / gate & Status \\",
        r"\midrule",
    ]
    for risk in register["risks"]:
        first = (
            rf"\textbf{{{tex_escape(risk['title'])}}}\newline "
            rf"\textit{{{tex_escape(risk['evidence_layer'])}}}"
        )
        gate = (
            tex_escape(risk["residual_risk"])
            + r"\newline \textit{Owner: }"
            + tex_escape(risk["owner"])
            + r"."
            + r"\newline \textit{Gate: }"
            + tex_escape(risk["blocking_gate"])
            + "."
        )
        lines.append(
            " & ".join(
                (
                    first,
                    tex_escape(risk["current_control"]),
                    gate,
                    rf"\textbf{{{STATUS_LABELS[risk['status']]}}}",
                )
            )
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}%",
            r"\par\smallskip",
            r"{\raggedright\scriptsize \textbf{Status key.} Mixed = only named "
            r"synthetic behavior is implemented; Specified = required but unverified; "
            r"Unresolved = no adequate control or evidence is registered; Blocked = "
            r"the activity cannot proceed before the stated gate. Every row retains "
            r"residual uncertainty.\par}",
            "",
        ]
    )
    return "\n".join(lines)


def expected_outputs(project: Path = ROOT) -> dict[Path, str]:
    """Return the governed output path and its expected content."""
    return {project / OUTPUT_PATH: render_table(load_register(project))}


def main() -> int:
    """Write or check the deterministic table projection."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", default=str(ROOT))
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    project = Path(arguments.project).expanduser().resolve()
    outputs = expected_outputs(project)
    if arguments.write:
        for path, content in outputs.items():
            path.write_text(content, encoding="utf-8")
        print("WROTE governed risk table")
        return 0
    stale = [
        path
        for path, content in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    if stale:
        for path in stale:
            print(f"ERROR generated risk table is stale: {path.relative_to(project)}")
        return 1
    print("PASS governed risk register and table")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
