#!/usr/bin/env python3
# Copyright 2026 Ego Hygiene
# SPDX-License-Identifier: MIT

"""Render the governed research-landscape table from the comparator matrix."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "research" / "sources" / "comparator-novelty-matrix.json"
OUTPUT_PATH = ROOT / "paper" / "tables" / "research-landscape-comparator.tex"

SOURCE_ORDER = (
    "mindmelody-2605.01235",
    "daly-abcmi-046022",
    "ehrlich-closed-loop-0213516",
    "affectmachine-classical-1158172",
    "personalized-affective-music-player-9107",
    "beamers-2211.14609",
    "mallik-russo-auditory-beats-0259312",
    "iheartlift-6090277",
    "minimalist-bcmi-2606.01473",
)

SOURCE_LABELS = {
    "mindmelody-2605.01235": ("MindMelody", "zhang2026mindmelody"),
    "daly-abcmi-046022": ("Daly aBCMI", "daly2016abcmi"),
    "ehrlich-closed-loop-0213516": ("Ehrlich BCI", "ehrlich2019closedloop"),
    "affectmachine-classical-1158172": (
        "AffectMachine",
        "agres2023affectmachine",
    ),
    "personalized-affective-music-player-9107": (
        "Affective player",
        "janssen2012tune",
    ),
    "beamers-2211.14609": ("BEAMERS", "li2022beamers"),
    "mallik-russo-auditory-beats-0259312": ("LUCID", "mallik2022effects"),
    "iheartlift-6090277": ("iHeartLift", "ho2011iheartlift"),
    "minimalist-bcmi-2606.01473": ("Minimalist BCMI", "monroy2026minimalist"),
}

DIMENSIONS = (
    ("semantic_representation", "Sem."),
    ("journey_representation", "Journey"),
    ("audio_strategy", "Audio"),
    ("within_session_adaptation", "Loop"),
    ("longitudinal_learning", "Longit."),
    ("provenance", "Prov."),
)

STATUS_TOKENS = {
    "reported": "R",
    "partial": "P",
    "proposed": "Prop.",
    "not-reported": "NR",
    "not-applicable": "NA",
}


def load_matrix(path: Path = MATRIX_PATH) -> dict:
    """Load and minimally validate the canonical comparator matrix."""
    matrix = json.loads(path.read_text(encoding="utf-8"))
    if matrix.get("schema") != "antidote.comparator-novelty-matrix/v1":
        raise ValueError("unexpected comparator matrix schema")
    return matrix


def render_table(matrix: dict) -> str:
    """Return a compact LaTeX projection with explicit support-state tokens."""
    comparators = {
        comparator["source_id"]: comparator
        for comparator in matrix.get("comparators", [])
    }
    missing = sorted(set(SOURCE_ORDER) - set(comparators))
    extra = sorted(set(comparators) - set(SOURCE_ORDER))
    if missing or extra:
        raise ValueError(
            f"comparator roster drifted; missing={missing}, extra={extra}"
        )

    lines = [
        "% Generated by scripts/generate_comparator_table.py.",
        "% Source: research/sources/comparator-novelty-matrix.json.",
        "% Do not edit this projection by hand.",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.7pt}%",
        r"\begin{tabular}{@{}lcccccc@{}}",
        r"\toprule",
        "System & "
        + " & ".join(f"\\textbf{{{heading}}}" for _, heading in DIMENSIONS)
        + r" \\",
        r"\midrule",
    ]

    for source_id in SOURCE_ORDER:
        comparator = comparators[source_id]
        label, citation = SOURCE_LABELS[source_id]
        cells = []
        for dimension, _ in DIMENSIONS:
            status = comparator["dimensions"][dimension]["status"]
            try:
                cells.append(STATUS_TOKENS[status])
            except KeyError as error:
                raise ValueError(
                    f"{source_id} has unsupported {dimension} status: {status}"
                ) from error
        lines.append(
            f"{label} \\citep{{{citation}}} & " + " & ".join(cells) + r" \\"
        )

    lines.extend(
        [
            r"\midrule",
            r"\textbf{Antidote profile} & Prop. & Prop. & Prop. & Prop. & Prop. & Prop. \\",
            r"\bottomrule",
            r"\end{tabular}%",
            r"\par\smallskip",
            r"{\raggedright\scriptsize R = reported; P = partial; NR = not reported in the reviewed artifact; NA = not applicable; Prop. = proposed, not evaluated. A token identifies reported capability only, not evidence strength, implementation quality, safety, or benefit.\par}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Write the projection or check that the tracked artifact is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the tracked table differs from the canonical projection",
    )
    arguments = parser.parse_args()
    rendered = render_table(load_matrix())
    if arguments.check:
        if (
            not OUTPUT_PATH.is_file()
            or OUTPUT_PATH.read_text(encoding="utf-8") != rendered
        ):
            raise SystemExit(
                "research landscape table is stale; run "
                "python3 scripts/generate_comparator_table.py"
            )
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
