#!/usr/bin/env python3
# Copyright 2026 Ego Hygiene
# SPDX-License-Identifier: MIT

"""Generate the visibly separate additional-reading shelf for the paper."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = Path("research/sources/catalog.json")
BIBLIOGRAPHY_PATH = Path("paper/references.bib")
OUTPUT_PATH = Path("paper/research-shelf.tex")
ENTRY_START = re.compile(r"@\w+\s*\{\s*([^,\s]+)", re.IGNORECASE)
CITATION = re.compile(r"\\cite\w*\*?(?:\[[^\]]*\]){0,2}\{([^}]+)\}")


def tex_escape(value: object) -> str:
    """Escape plain catalog text for deterministic LaTeX inclusion."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    normalized = re.sub(r"\s+", " ", str(value)).strip()
    return "".join(replacements.get(character, character) for character in normalized)


def citation_keys(project: Path) -> set[str]:
    """Return direct manuscript citations without inspecting generated shelf text."""
    citations: set[str] = set()
    for path in sorted((project / "paper" / "sections").glob("*.tex")):
        text = path.read_text(encoding="utf-8")
        for group in CITATION.findall(text):
            citations.update(key.strip() for key in group.split(",") if key.strip())
    return citations


def bibliography_keys(project: Path) -> set[str]:
    """Return every verified key preserved in the bibliography shelf."""
    text = (project / BIBLIOGRAPHY_PATH).read_text(encoding="utf-8")
    return set(ENTRY_START.findall(text))


def render_shelf(project: Path = ROOT) -> str:
    """Render catalog-backed entries that are useful but not directly cited."""
    catalog = json.loads((project / CATALOG_PATH).read_text(encoding="utf-8"))
    known_keys = bibliography_keys(project)
    cited = citation_keys(project)
    records = [
        source
        for source in catalog["sources"]
        if source.get("bibliography_key") in known_keys
        and source.get("bibliography_key") not in cited
    ]
    records.sort(key=lambda source: str(source["working_title"]).casefold())
    lines = [
        "% Generated by scripts/generate_research_shelf.py.",
        "% Source: research/sources/catalog.json and paper/references.bib.",
        "% These entries are additional reading, not direct manuscript citations.",
        "",
        rf"\noindent\textit{{{len(cited)} directly cited works; {len(records)} additional verified bibliography entries; {len(catalog['sources'])} total living-atlas records.}}",
        "",
        r"\begin{itemize}[leftmargin=1.25em,itemsep=0.75em]",
    ]
    for source in records:
        key = tex_escape(source["bibliography_key"])
        title = tex_escape(source["working_title"])
        source_class = tex_escape(source["source_class"])
        status = tex_escape(source["status"])
        domains = tex_escape(", ".join(source["domains"]))
        url = source["canonical_url"]
        lines.extend(
            [
                rf"  \item \texttt{{{key}}}\par \href{{{url}}}{{{title}}}.",
                rf"  \textit{{Catalog class: {source_class}; state: {status}.}} Domains: {domains}.",
            ]
        )
    lines.extend([r"\end{itemize}", ""])
    return "\n".join(lines)


def main() -> int:
    """Write or verify the committed additional-reading projection."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", default=str(ROOT))
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    project = Path(arguments.project).expanduser().resolve()
    destination = project / OUTPUT_PATH
    expected = render_shelf(project)
    if arguments.write:
        destination.write_text(expected, encoding="utf-8")
        print(f"WROTE {destination}")
        return 0
    if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
        print(
            "ERROR additional-reading shelf is missing or stale; "
            "run scripts/generate_research_shelf.py --write",
            file=sys.stderr,
        )
        return 1
    print("PASS additional-reading shelf is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
