#!/usr/bin/env python3
# Copyright 2026 Ego Hygiene
# SPDX-License-Identifier: MIT

"""Generate Antidote's non-result scientific visual tables."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EPISTEMOLOGY_PATH = Path("EPISTEMOLOGY.md")
PROTOCOL_PATH = Path("experiments/protocols/antidote-feasibility-v1.1.json")
PROTOCOL_LOCK_PATH = Path("experiments/protocols/antidote-feasibility-v1.1.lock.json")
REPORTING_PATH = Path("experiments/reporting/results-reporting-v1.1.json")


def tex_escape(value: object) -> str:
    """Escape plain text for deterministic LaTeX."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in str(value))


def load_json(project: Path, relative: Path) -> dict[str, object]:
    """Load one repository-owned JSON object."""
    value = json.loads((project / relative).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object: {relative}")
    return value


def evidence_rows(project: Path) -> list[tuple[str, str]]:
    """Read the five canonical evidence classes from EPISTEMOLOGY.md."""
    source = (project / EPISTEMOLOGY_PATH).read_text(encoding="utf-8")
    lines = source.splitlines()
    try:
        header_index = lines.index("| Layer | Meaning |")
    except ValueError as error:
        raise ValueError("cannot find the canonical five-row evidence table")
    candidates = lines[header_index + 2 : header_index + 7]
    rows: list[tuple[str, str]] = []
    for line in candidates:
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) == 2:
            rows.append((cells[0], cells[1]))
    if [name for name, _ in rows] != [
        "Source",
        "Hypothesis",
        "Observation",
        "Interpretation",
        "Claim",
    ]:
        raise ValueError("canonical evidence classes or ordering changed")
    return rows


def evidence_classification_table(project: Path) -> str:
    """Project evidence classes with support and promotion boundaries."""
    support = {
        "Source": "Primary or authoritative work plus a reviewed source record.",
        "Hypothesis": "Scoped rationale, uncertainty, and a testable research question.",
        "Observation": "A qualifying artifact, protocol, measurement, or person report.",
        "Interpretation": "Explicit reasoning linked to evidence and alternatives.",
        "Claim": "Ledger ID, named evidence, permitted wording, and review disposition.",
    }
    promotion = {
        "Source": "Supports only what the source establishes; never promotes itself to an Antidote claim.",
        "Hypothesis": "Remains tentative until qualifying observations and prespecified analysis exist.",
        "Observation": "Does not become an interpretation, outcome, or generalized claim automatically.",
        "Interpretation": "Must retain uncertainty, conflict, and plausible alternatives.",
        "Claim": "Must stay within its ledger boundary; otherwise downgrade, revise, or reject.",
    }
    lines = [
        "% Generated by scripts/generate_visual_tables.py.",
        "% Source: EPISTEMOLOGY.md and research/notes/CLAIM_LEDGER.md.",
        "% Do not edit this projection by hand.",
        r"\small",
        r"\setlength{\tabcolsep}{3.5pt}%",
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.15\linewidth}>{\raggedright\arraybackslash}p{0.27\linewidth}>{\raggedright\arraybackslash}p{0.27\linewidth}>{\raggedright\arraybackslash}p{0.25\linewidth}@{}}",
        r"\toprule",
        r"\textbf{Class} & \textbf{Meaning} & \textbf{Acceptable support} & \textbf{Promotion boundary} \\",
        r"\midrule",
    ]
    for name, meaning in evidence_rows(project):
        lines.append(
            f"\\textbf{{{tex_escape(name)}}} & {tex_escape(meaning)} & "
            f"{tex_escape(support[name])} & {tex_escape(promotion[name])} \\\\"
        )
        lines.append(r"\addlinespace[0.32em]")
    lines.extend(
        (
            r"\bottomrule",
            r"\end{tabular}%",
            r"\par\smallskip",
            r"{\raggedright\scriptsize Each promotion is a separately reviewed decision. A generated explanation is not a source, and a synthetic fixture or compelling experience is not automatically a human-outcome result.\par}",
            "",
        )
    )
    return "\n".join(lines)


MEASUREMENT_COMPACT = {
    "MEAS-BASELINE-STATE": (
        "Text + valence/arousal [-1,1] + intensity [0,1].",
        "moment-context.current_state",
    ),
    "MEAS-DESIRED-TRANSITION": (
        "Selected category + required text; nominal, not ordinal.",
        "moment-context.desired_transition",
    ),
    "MEAS-SEMANTIC-CONTROLS": (
        "Approved projection + plan revision; typed edits and exclusions.",
        "working-context + journey-plan",
    ),
    "MEAS-ACOUSTIC-REALIZATION": (
        "Artifact verifier + feature analyzer; feature-specific units and warnings.",
        "generation-result",
    ),
    "MEAS-EXPOSURE": (
        "Playback event; artifact hash, timestamps, seconds heard, and stop state.",
        "core Exposure event",
    ),
    "MEAS-PERCEIVED-EXPRESSION": (
        "Optional text + valence/arousal [-1,1] + intensity [0,1].",
        "response-v2.perceived_expression",
    ),
    "MEAS-FELT-STATE": (
        "Optional text + valence/arousal [-1,1] + intensity [0,1]; field missingness.",
        "response-v2.felt_state",
    ),
    "MEAS-APPRAISAL": (
        "Wanted intensity yes/no/unsure; helpfulness, resonance, mismatch, harm, surprise [0,1].",
        "response-v2 appraisal fields",
    ),
    "MEAS-BURDEN": (
        "Interaction burden + whole-session burden [0,1].",
        "response-v2 burden fields",
    ),
    "MEAS-AFTEREFFECT": (
        "Ongoing effect yes/no/unsure + optional later meaning.",
        "response-v2 aftereffect fields",
    ),
    "MEAS-MISSINGNESS": (
        "Per-field reason: not prompted, declined, missed, failed, interrupted, or not applicable.",
        "response-v2.missingness",
    ),
    "MEAS-CORRECTION": (
        "Append-only revision, superseded response ID, and person-authored reason.",
        "response-v2 correction lineage",
    ),
    "MEAS-CLINICAL": (
        "No instrument; not collected; not applicable.",
        "explicit unavailable state",
    ),
}


def verified_protocol(project: Path) -> tuple[dict[str, object], dict[str, object]]:
    """Load the frozen protocol only when its identity and digest remain exact."""
    protocol = load_json(project, PROTOCOL_PATH)
    lock = load_json(project, PROTOCOL_LOCK_PATH)
    digest = hashlib.sha256((project / PROTOCOL_PATH).read_bytes()).hexdigest()
    if protocol.get("protocol_id") != "ANT-PROT-FEAS-001":
        raise ValueError("unexpected feasibility protocol ID")
    if protocol.get("version") != "1.1.0" or lock.get("protocol_version") != "1.1.0":
        raise ValueError("unexpected feasibility protocol version")
    if digest != lock.get("sha256"):
        raise ValueError("feasibility protocol digest does not match its lock")
    if protocol.get("collection_authority") is not False:
        raise ValueError("visual production cannot activate collection authority")
    return protocol, lock


def measurement_matrix(project: Path) -> str:
    """Project the complete frozen measurement registry in compact form."""
    protocol, _ = verified_protocol(project)
    registry = protocol.get("measurement_registry")
    if not isinstance(registry, list):
        raise ValueError("measurement_registry must be an array")
    ids = [row.get("id") for row in registry if isinstance(row, dict)]
    if ids != list(MEASUREMENT_COMPACT):
        raise ValueError("measurement registry IDs or order changed")
    lines = [
        "% Generated by scripts/generate_visual_tables.py.",
        "% Source: experiments/protocols/antidote-feasibility-v1.1.json.",
        "% Do not edit this projection by hand.",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.5pt}%",
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.20\linewidth}>{\raggedright\arraybackslash}p{0.20\linewidth}>{\raggedright\arraybackslash}p{0.32\linewidth}>{\raggedright\arraybackslash}p{0.23\linewidth}@{}}",
        r"\toprule",
        r"\textbf{Registry ID / construct} & \textbf{Timing / evidence} & \textbf{Instrument, scale, provenance} & \textbf{Strongest permitted boundary} \\",
        r"\midrule",
    ]
    for row in registry:
        assert isinstance(row, dict)
        identifier = str(row["id"])
        instrument, provenance = MEASUREMENT_COMPACT[identifier]
        lines.append(
            f"{{\\tiny\\nolinkurl{{{tex_escape(identifier)}}}}}\\newline "
            f"{tex_escape(row['construct'])} & "
            f"{tex_escape(row['timing'])}\\newline {{\\tiny {tex_escape(row['evidence_class'])}}} & "
            f"{tex_escape(instrument)}\\newline {{\\tiny Source: {tex_escape(provenance)}}} & "
            f"{tex_escape(row['prohibited_inference'])} \\\\"
        )
        lines.append(r"\addlinespace[0.20em]")
    lines.extend(
        (
            r"\bottomrule",
            r"\end{tabular}%",
            r"\par\smallskip",
            r"{\raggedright\scriptsize Prospective projection of \texttt{ANT-PROT-FEAS-001} v1.1.0. Collection authority is false. Scale shorthand preserves the frozen anchors; prompted but absent fields retain explicit missingness rather than a substituted value.\par}",
            "",
        )
    )
    return "\n".join(lines)


def protocol_audit(project: Path) -> str:
    """Project the current protocol, reporting, and evidence availability audit."""
    protocol, lock = verified_protocol(project)
    reporting = load_json(project, REPORTING_PATH)
    if reporting.get("reporting_id") != "ANT-REPORT-RESULTS-001":
        raise ValueError("unexpected results-reporting contract ID")
    if reporting.get("version") != "1.1.0":
        raise ValueError("unexpected results-reporting contract version")
    if reporting.get("status") != "governed-empty-reporting-contract":
        raise ValueError("results-reporting contract is no longer an empty state")
    reporting_digest = hashlib.sha256((project / REPORTING_PATH).read_bytes()).hexdigest()
    stages = protocol.get("stages")
    if not isinstance(stages, list) or [stage.get("id") for stage in stages] != ["D0", "T0", "T1", "H1"]:
        raise ValueError("protocol stage ladder changed")
    rows = [
        (
            "Protocol lock",
            "ANT-PROT-FEAS-001 v1.1.0",
            f"SHA-256 {str(lock['sha256'])[:16]}…",
            "Decided: frozen prospective design",
            "Collection authority false; no qualifying record started.",
        ),
        (
            "Reporting contract",
            "ANT-REPORT-RESULTS-001 v1.1.0",
            f"SHA-256 {reporting_digest[:16]}…",
            "Repository observation: governed empty state",
            "No T0, T1, or H1 source package is registered; unavailable is not zero.",
        ),
    ]
    for stage in stages:
        assert isinstance(stage, dict)
        stage_id = str(stage["id"])
        if stage_id == "D0":
            source = "manuscript + ledgers"
        elif stage_id == "T0":
            source = "ANT-REC-T0-001 absent"
        elif stage_id == "T1":
            source = "ANT-REC-T1-001 absent"
        else:
            source = "public H1 envelopes absent"
        gate = str(stage["entry_gate"])
        if stage_id == "H1":
            gate = (
                "All H1 activation gates require independent satisfaction "
                "under a new activation record."
            )
        rows.append(
            (
                f"{stage_id}: {stage['name']}",
                str(stage["current_state"]),
                source,
                str(stage["evidence_class"]),
                gate,
            )
        )
    rows.append(
        (
            "Claim promotion",
            "ANT-CLM-006 / ANT-CLM-007",
            "claim ledger",
            "Accepted artifact claims only",
            "RQ2 and RQ3 remain unanswered; later evidence needs separate promotion review.",
        )
    )
    lines = [
        "% Generated by scripts/generate_visual_tables.py.",
        "% Sources: frozen protocol, lock, reporting contract, and claim ledger.",
        "% Do not edit this projection by hand.",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{2.7pt}%",
        r"\begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.18\linewidth}>{\raggedright\arraybackslash}p{0.19\linewidth}>{\raggedright\arraybackslash}p{0.17\linewidth}>{\raggedright\arraybackslash}p{0.19\linewidth}>{\raggedright\arraybackslash}p{0.21\linewidth}@{}}",
        r"\toprule",
        r"\textbf{Audit row} & \textbf{Version / state} & \textbf{Identity / source} & \textbf{Evidence class} & \textbf{Boundary or gate} \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(tex_escape(cell) for cell in row) + r" \\")
        lines.append(r"\addlinespace[0.26em]")
    lines.extend(
        (
            r"\bottomrule",
            r"\end{tabular}%",
            r"\par\smallskip",
            r"{\raggedright\scriptsize Digests identify the exact local artifacts used by this projection. They support integrity inspection, not truth, privacy, safety, ownership, or efficacy. No private or participant record is represented.\par}",
            "",
        )
    )
    return "\n".join(lines)


def expected_assets(project: Path = ROOT) -> dict[Path, str]:
    """Return the exact generated visual-table paths and contents."""
    return {
        Path("paper/tables/evidence-claim-classification.tex"): evidence_classification_table(project),
        Path("paper/tables/measurement-evidence-matrix.tex"): measurement_matrix(project),
        Path("paper/tables/protocol-evidence-audit.tex"): protocol_audit(project),
    }


def main() -> int:
    """Write or verify the generated visual tables."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", default=str(ROOT))
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    project = Path(arguments.project).expanduser().resolve()
    stale: list[str] = []
    try:
        assets = expected_assets(project)
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"ERROR visual tables cannot be generated: {error}", file=sys.stderr)
        return 1
    for relative, expected in assets.items():
        destination = project / relative
        if arguments.write:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(expected, encoding="utf-8")
        elif not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
            stale.append(str(relative))
    if stale:
        for relative in stale:
            print(f"ERROR generated visual table is stale or missing: {relative}", file=sys.stderr)
        return 1
    action = "wrote" if arguments.write else "verified"
    print(f"PASS {action} {len(assets)} deterministic visual tables.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
