// @generated by scripts/generate_contracts.py; DO NOT EDIT.

#![allow(clippy::module_name_repetitions)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantAction {
    #[serde(rename = "inspect")]
    Inspect,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "generate")]
    Generate,
    #[serde(rename = "retain")]
    Retain,
    #[serde(rename = "learn")]
    Learn,
    #[serde(rename = "export")]
    Export,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantPurpose {
    #[serde(rename = "journey_planning")]
    JourneyPlanning,
    #[serde(rename = "generation")]
    Generation,
    #[serde(rename = "response_capture")]
    ResponseCapture,
    #[serde(rename = "personal_learning")]
    PersonalLearning,
    #[serde(rename = "research_export")]
    ResearchExport,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantRetentionMode {
    #[serde(rename = "session_only")]
    SessionOnly,
    #[serde(rename = "until_expiry")]
    UntilExpiry,
    #[serde(rename = "until_manual_deletion")]
    UntilManualDeletion,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantSourceSourceType {
    #[serde(rename = "manual_entry")]
    ManualEntry,
    #[serde(rename = "journal_excerpt")]
    JournalExcerpt,
    #[serde(rename = "therapy_chat_excerpt")]
    TherapyChatExcerpt,
    #[serde(rename = "prior_session")]
    PriorSession,
    #[serde(rename = "imported_note")]
    ImportedNote,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationResultArtifactKind {
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "preview")]
    Preview,
    #[serde(rename = "feature_report")]
    FeatureReport,
    #[serde(rename = "log")]
    Log,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationResultStatus {
    #[serde(rename = "generated")]
    Generated,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationSpecOutputFormat {
    #[serde(rename = "wav")]
    Wav,
    #[serde(rename = "flac")]
    Flac,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanControlPolicySupportedControl {
    #[serde(rename = "tempo_bpm")]
    TempoBpm,
    #[serde(rename = "key")]
    Key,
    #[serde(rename = "time_signature")]
    TimeSignature,
    #[serde(rename = "timbre")]
    Timbre,
    #[serde(rename = "harmony")]
    Harmony,
    #[serde(rename = "density")]
    Density,
    #[serde(rename = "spatiality")]
    Spatiality,
    #[serde(rename = "dynamics")]
    Dynamics,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanDerivationSource {
    #[serde(rename = "rule")]
    Rule,
    #[serde(rename = "person_edit")]
    PersonEdit,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanStageRole {
    #[serde(rename = "meet")]
    Meet,
    #[serde(rename = "hold")]
    Hold,
    #[serde(rename = "transition")]
    Transition,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "integrate")]
    Integrate,
    #[serde(rename = "close")]
    Close,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MomentContextDesiredTransitionDirection {
    #[serde(rename = "stay_with")]
    StayWith,
    #[serde(rename = "soften")]
    Soften,
    #[serde(rename = "regulate")]
    Regulate,
    #[serde(rename = "uplift")]
    Uplift,
    #[serde(rename = "focus")]
    Focus,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "explore")]
    Explore,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationWindow {
    #[serde(rename = "during")]
    During,
    #[serde(rename = "immediate")]
    Immediate,
    #[serde(rename = "later")]
    Later,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkingContextProjectionSemanticItemKind {
    #[serde(rename = "state")]
    State,
    #[serde(rename = "meaning")]
    Meaning,
    #[serde(rename = "metaphor")]
    Metaphor,
    #[serde(rename = "memory")]
    Memory,
    #[serde(rename = "preference")]
    Preference,
    #[serde(rename = "inclusion")]
    Inclusion,
    #[serde(rename = "exclusion")]
    Exclusion,
    #[serde(rename = "constraint")]
    Constraint,
    #[serde(rename = "uncertainty")]
    Uncertainty,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkingContextProjectionSemanticItemUserReview {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "edited")]
    Edited,
    #[serde(rename = "excluded")]
    Excluded,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrant {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub status: ConsentGrantStatus,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub purposes: Vec<ConsentGrantPurpose>,
    pub actions: Vec<ConsentGrantAction>,
    pub sources: Vec<ConsentGrantSource>,
    pub retention: ConsentGrantRetention,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantRetention {
    pub mode: ConsentGrantRetentionMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_derived_projection: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_personal_model_update: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantSource {
    pub source_id: String,
    pub source_type: ConsentGrantSourceSourceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResult {
    pub schema_version: String,
    pub id: String,
    pub generation_spec_id: String,
    pub status: GenerationResultStatus,
    pub adapter: GenerationResultAdapter,
    pub model: GenerationResultModel,
    pub code_revision: String,
    pub device_class: String,
    pub elapsed_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_parameters: Option<serde_json::Value>,
    pub artifacts: Vec<GenerationResultArtifact>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feature_report: Option<GenerationResultFeatureReport>,
    pub warnings: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure: Option<GenerationResultFailure>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultAdapter {
    pub id: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultArtifact {
    pub kind: GenerationResultArtifactKind,
    pub path: String,
    pub sha256: String,
    pub media_type: String,
    pub size_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultFailure {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GenerationResultFeatureReport {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tempo_bpm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub loudness_lufs: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_adherence: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub analyzer_versions: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultModel {
    pub id: String,
    pub revision: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpec {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub journey_plan_id: String,
    pub journey_plan_hash: String,
    pub adapter: GenerationSpecAdapter,
    pub model: GenerationSpecModel,
    pub duration_seconds: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub negative_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_capabilities: Option<Vec<String>>,
    pub output: GenerationSpecOutput,
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecAdapter {
    pub id: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecModel {
    pub id: String,
    pub revision: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecOutput {
    pub format: GenerationSpecOutputFormat,
    pub sample_rate_hz: i64,
    pub channels: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlan {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub moment_context_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_projection_id: Option<String>,
    pub status: JourneyPlanStatus,
    pub strategy: String,
    pub total_duration_seconds: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supersedes_plan_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rule_set: Option<JourneyPlanRuleSet>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_policy: Option<JourneyPlanControlPolicy>,
    pub stages: Vec<JourneyPlanStage>,
    pub safety_constraints: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub derivations: Option<Vec<JourneyPlanDerivation>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approved_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanControlPolicy {
    pub supported_controls: Vec<JourneyPlanControlPolicySupportedControl>,
    pub stagewise_controls: bool,
    pub tempo_bpm_min: f64,
    pub tempo_bpm_max: f64,
    pub density_ceiling: f64,
    pub spatiality_ceiling: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanDerivation {
    pub target: String,
    pub source: JourneyPlanDerivationSource,
    pub rule_id: String,
    pub rationale: String,
    pub uncertainty: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanRuleSet {
    pub id: String,
    pub version: String,
    pub input_hash: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanStage {
    pub id: String,
    pub order: i64,
    pub role: JourneyPlanStageRole,
    pub duration_seconds: i64,
    pub semantic_intent: Vec<String>,
    pub acoustic_controls: JourneyPlanStageAcousticControls,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transition_rationale: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanStageAcousticControls {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tempo_bpm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_signature: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timbre: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub harmony: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spatiality: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dynamics: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContext {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub observed_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_projection_id: Option<String>,
    pub current_state: MomentContextState,
    pub desired_transition: MomentContextDesiredTransition,
    pub time_horizon_seconds: i64,
    pub inclusions: Vec<String>,
    pub exclusions: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContextDesiredTransition {
    pub direction: MomentContextDesiredTransitionDirection,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_state: Option<MomentContextState>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContextState {
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arousal: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservation {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub exposure_id: String,
    pub observed_at: String,
    pub window: ResponseObservationWindow,
    pub felt_state: ResponseObservationFeltState,
    pub wanted_intensity: Option<bool>,
    pub helpfulness: Option<f64>,
    pub resonance: Option<f64>,
    pub mismatch: Option<f64>,
    pub harm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stopped_early: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_personal_model_update: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationFeltState {
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arousal: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkingContextProjection {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub consent_grant_ids: Vec<String>,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub derivation_version: String,
    pub source_event_ids: Vec<String>,
    pub semantic_items: Vec<WorkingContextProjectionSemanticItem>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub projection_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkingContextProjectionSemanticItem {
    pub id: String,
    pub kind: WorkingContextProjectionSemanticItemKind,
    pub text: String,
    pub source_event_ids: Vec<String>,
    pub user_review: WorkingContextProjectionSemanticItemUserReview,
}

pub const CONTRACT_SCHEMAS: &[crate::ContractSchema] = &[
    crate::ContractSchema {
        name: "consent-grant",
        filename: "schemas/consent-grant.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:consent-grant:v1",
        document: include_str!("../../../contracts/schemas/consent-grant.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "generation-result",
        filename: "schemas/generation-result.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:generation-result:v1",
        document: include_str!("../../../contracts/schemas/generation-result.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "generation-spec",
        filename: "schemas/generation-spec.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:generation-spec:v1",
        document: include_str!("../../../contracts/schemas/generation-spec.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "journey-plan",
        filename: "schemas/journey-plan.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:journey-plan:v1",
        document: include_str!("../../../contracts/schemas/journey-plan.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "moment-context",
        filename: "schemas/moment-context.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:moment-context:v1",
        document: include_str!("../../../contracts/schemas/moment-context.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "response-observation",
        filename: "schemas/response-observation.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:response-observation:v1",
        document: include_str!("../../../contracts/schemas/response-observation.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "working-context-projection",
        filename: "schemas/working-context-projection.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:working-context-projection:v1",
        document: include_str!(
            "../../../contracts/schemas/working-context-projection.v1.schema.json"
        ),
    },
];
