// @generated by scripts/generate_contracts.py; DO NOT EDIT.

#![allow(clippy::module_name_repetitions)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantAction {
    #[serde(rename = "inspect")]
    Inspect,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "generate")]
    Generate,
    #[serde(rename = "retain")]
    Retain,
    #[serde(rename = "learn")]
    Learn,
    #[serde(rename = "export")]
    Export,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantPurpose {
    #[serde(rename = "journey_planning")]
    JourneyPlanning,
    #[serde(rename = "generation")]
    Generation,
    #[serde(rename = "response_capture")]
    ResponseCapture,
    #[serde(rename = "personal_learning")]
    PersonalLearning,
    #[serde(rename = "research_export")]
    ResearchExport,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantRetentionMode {
    #[serde(rename = "session_only")]
    SessionOnly,
    #[serde(rename = "until_expiry")]
    UntilExpiry,
    #[serde(rename = "until_manual_deletion")]
    UntilManualDeletion,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantSourceSourceType {
    #[serde(rename = "manual_entry")]
    ManualEntry,
    #[serde(rename = "journal_excerpt")]
    JournalExcerpt,
    #[serde(rename = "therapy_chat_excerpt")]
    TherapyChatExcerpt,
    #[serde(rename = "prior_session")]
    PriorSession,
    #[serde(rename = "imported_note")]
    ImportedNote,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantV2Action {
    #[serde(rename = "inspect")]
    Inspect,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "generate")]
    Generate,
    #[serde(rename = "analyze")]
    Analyze,
    #[serde(rename = "play")]
    Play,
    #[serde(rename = "retain")]
    Retain,
    #[serde(rename = "learn")]
    Learn,
    #[serde(rename = "export")]
    Export,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantV2Purpose {
    #[serde(rename = "journey_planning")]
    JourneyPlanning,
    #[serde(rename = "generation")]
    Generation,
    #[serde(rename = "response_capture")]
    ResponseCapture,
    #[serde(rename = "personal_learning")]
    PersonalLearning,
    #[serde(rename = "research_export")]
    ResearchExport,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantV2RetentionMode {
    #[serde(rename = "session_only")]
    SessionOnly,
    #[serde(rename = "until_expiry")]
    UntilExpiry,
    #[serde(rename = "until_manual_deletion")]
    UntilManualDeletion,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantV2SourceSourceType {
    #[serde(rename = "manual_entry")]
    ManualEntry,
    #[serde(rename = "journal_excerpt")]
    JournalExcerpt,
    #[serde(rename = "therapy_chat_excerpt")]
    TherapyChatExcerpt,
    #[serde(rename = "prior_session")]
    PriorSession,
    #[serde(rename = "imported_note")]
    ImportedNote,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConsentGrantV2Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationResultArtifactKind {
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "preview")]
    Preview,
    #[serde(rename = "feature_report")]
    FeatureReport,
    #[serde(rename = "log")]
    Log,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationResultStatus {
    #[serde(rename = "generated")]
    Generated,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum GenerationSpecOutputFormat {
    #[serde(rename = "wav")]
    Wav,
    #[serde(rename = "flac")]
    Flac,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeAggregateAccountingStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeAmendmentStatusStatus {
    #[serde(rename = "absent")]
    Absent,
    #[serde(rename = "approved")]
    Approved,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeAssignmentCommitmentStatus {
    #[serde(rename = "committed")]
    Committed,
    #[serde(rename = "not-activated")]
    NotActivated,
    #[serde(rename = "unavailable")]
    Unavailable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeEvidenceClass {
    #[serde(rename = "human-aggregate")]
    HumanAggregate,
    #[serde(rename = "unavailable")]
    Unavailable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeNumericSummaryStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeNumericSummaryUnit {
    #[serde(rename = "count")]
    Count,
    #[serde(rename = "proportion")]
    Proportion,
    #[serde(rename = "seconds")]
    Seconds,
    #[serde(rename = "milliseconds")]
    Milliseconds,
    #[serde(rename = "score")]
    Score,
    #[serde(rename = "correlation")]
    Correlation,
    #[serde(rename = "dimensionless")]
    Dimensionless,
    #[serde(rename = "bpm")]
    Bpm,
    #[serde(rename = "lufs")]
    Lufs,
    #[serde(rename = "dbtp")]
    Dbtp,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopePackageKind {
    #[serde(rename = "flow")]
    Flow,
    #[serde(rename = "response")]
    Response,
    #[serde(rename = "safety")]
    Safety,
    #[serde(rename = "audit")]
    Audit,
    #[serde(rename = "physiology")]
    Physiology,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopePrivacyReviewStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "passed")]
    Passed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeProgressionDisposition {
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "revise")]
    Revise,
    #[serde(rename = "proceed")]
    Proceed,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopePromotionDisposition {
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "not-promoted")]
    NotPromoted,
    #[serde(rename = "eligible-for-review")]
    EligibleForReview,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopePublicArtifactKind {
    #[serde(rename = "aggregate-table")]
    AggregateTable,
    #[serde(rename = "aggregate-figure")]
    AggregateFigure,
    #[serde(rename = "aggregate-audit-table")]
    AggregateAuditTable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopePublicArtifactMediaType {
    #[serde(rename = "application/json")]
    ApplicationJson,
    #[serde(rename = "text/csv")]
    TextCsv,
    #[serde(rename = "image/svg+xml")]
    ImageSvgXml,
    #[serde(rename = "image/png")]
    ImagePng,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum H1PublicResultEnvelopeSourceRecordId {
    #[serde(rename = "ANT-REC-H1-FLOW-001")]
    ANTRECH1FLOW001,
    #[serde(rename = "ANT-REC-H1-RESPONSE-001")]
    ANTRECH1RESPONSE001,
    #[serde(rename = "ANT-REC-H1-SAFETY-001")]
    ANTRECH1SAFETY001,
    #[serde(rename = "ANT-REC-H1-AUDIT-001")]
    ANTRECH1AUDIT001,
    #[serde(rename = "ANT-REC-H1-PHYS-001")]
    ANTRECH1PHYS001,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanControlPolicySupportedControl {
    #[serde(rename = "tempo_bpm")]
    TempoBpm,
    #[serde(rename = "key")]
    Key,
    #[serde(rename = "time_signature")]
    TimeSignature,
    #[serde(rename = "timbre")]
    Timbre,
    #[serde(rename = "harmony")]
    Harmony,
    #[serde(rename = "density")]
    Density,
    #[serde(rename = "spatiality")]
    Spatiality,
    #[serde(rename = "dynamics")]
    Dynamics,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanDerivationSource {
    #[serde(rename = "rule")]
    Rule,
    #[serde(rename = "person_edit")]
    PersonEdit,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanStageRole {
    #[serde(rename = "meet")]
    Meet,
    #[serde(rename = "hold")]
    Hold,
    #[serde(rename = "transition")]
    Transition,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "integrate")]
    Integrate,
    #[serde(rename = "close")]
    Close,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum JourneyPlanStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MomentContextDesiredTransitionDirection {
    #[serde(rename = "stay_with")]
    StayWith,
    #[serde(rename = "soften")]
    Soften,
    #[serde(rename = "regulate")]
    Regulate,
    #[serde(rename = "uplift")]
    Uplift,
    #[serde(rename = "focus")]
    Focus,
    #[serde(rename = "release")]
    Release,
    #[serde(rename = "explore")]
    Explore,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PrivateEvidenceIndexPrivateRecordAccountingStatus {
    #[serde(rename = "included")]
    Included,
    #[serde(rename = "excluded")]
    Excluded,
    #[serde(rename = "missing")]
    Missing,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PrivateEvidenceIndexPrivateRecordPackageScope {
    #[serde(rename = "flow")]
    Flow,
    #[serde(rename = "response")]
    Response,
    #[serde(rename = "safety")]
    Safety,
    #[serde(rename = "audit")]
    Audit,
    #[serde(rename = "physiology")]
    Physiology,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PrivateEvidenceIndexPrivateRecordReason {
    #[serde(rename = "not_prompted")]
    NotPrompted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "missed_window")]
    MissedWindow,
    #[serde(rename = "technical_failure")]
    TechnicalFailure,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "not_applicable")]
    NotApplicable,
    #[serde(rename = "protocol_exclusion")]
    ProtocolExclusion,
    #[serde(rename = "withdrawn")]
    Withdrawn,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum PrivateEvidenceIndexRetentionDisposition {
    #[serde(rename = "retained-private")]
    RetainedPrivate,
    #[serde(rename = "destroyed-with-tombstone")]
    DestroyedWithTombstone,
    #[serde(rename = "not-applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationMissingField {
    #[serde(rename = "perceived_expression")]
    PerceivedExpression,
    #[serde(rename = "felt_state")]
    FeltState,
    #[serde(rename = "wanted_intensity")]
    WantedIntensity,
    #[serde(rename = "helpfulness")]
    Helpfulness,
    #[serde(rename = "resonance")]
    Resonance,
    #[serde(rename = "mismatch")]
    Mismatch,
    #[serde(rename = "harm")]
    Harm,
    #[serde(rename = "surprise")]
    Surprise,
    #[serde(rename = "interaction_burden")]
    InteractionBurden,
    #[serde(rename = "session_burden")]
    SessionBurden,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationMissingnessReason {
    #[serde(rename = "not_prompted")]
    NotPrompted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "missed_window")]
    MissedWindow,
    #[serde(rename = "technical_failure")]
    TechnicalFailure,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "not_applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationV2MissingnessEntryField {
    #[serde(rename = "perceived_expression.description")]
    PerceivedExpressionDescription,
    #[serde(rename = "perceived_expression.valence")]
    PerceivedExpressionValence,
    #[serde(rename = "perceived_expression.arousal")]
    PerceivedExpressionArousal,
    #[serde(rename = "perceived_expression.intensity")]
    PerceivedExpressionIntensity,
    #[serde(rename = "felt_state.description")]
    FeltStateDescription,
    #[serde(rename = "felt_state.valence")]
    FeltStateValence,
    #[serde(rename = "felt_state.arousal")]
    FeltStateArousal,
    #[serde(rename = "felt_state.intensity")]
    FeltStateIntensity,
    #[serde(rename = "wanted_intensity")]
    WantedIntensity,
    #[serde(rename = "helpfulness")]
    Helpfulness,
    #[serde(rename = "resonance")]
    Resonance,
    #[serde(rename = "mismatch")]
    Mismatch,
    #[serde(rename = "harm")]
    Harm,
    #[serde(rename = "surprise")]
    Surprise,
    #[serde(rename = "interaction_burden")]
    InteractionBurden,
    #[serde(rename = "session_burden")]
    SessionBurden,
    #[serde(rename = "ongoing_effect")]
    OngoingEffect,
    #[serde(rename = "aftereffect_meaning")]
    AftereffectMeaning,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationV2MissingnessEntryReason {
    #[serde(rename = "not_prompted")]
    NotPrompted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "missed_window")]
    MissedWindow,
    #[serde(rename = "technical_failure")]
    TechnicalFailure,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "not_applicable")]
    NotApplicable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationV2OngoingEffect {
    #[serde(rename = "yes")]
    Yes,
    #[serde(rename = "no")]
    No,
    #[serde(rename = "unsure")]
    Unsure,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationV2WantedIntensity {
    #[serde(rename = "yes")]
    Yes,
    #[serde(rename = "no")]
    No,
    #[serde(rename = "unsure")]
    Unsure,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationV2Window {
    #[serde(rename = "immediate")]
    Immediate,
    #[serde(rename = "later")]
    Later,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResponseObservationWindow {
    #[serde(rename = "during")]
    During,
    #[serde(rename = "immediate")]
    Immediate,
    #[serde(rename = "later")]
    Later,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkingContextProjectionSemanticItemKind {
    #[serde(rename = "state")]
    State,
    #[serde(rename = "meaning")]
    Meaning,
    #[serde(rename = "metaphor")]
    Metaphor,
    #[serde(rename = "memory")]
    Memory,
    #[serde(rename = "preference")]
    Preference,
    #[serde(rename = "inclusion")]
    Inclusion,
    #[serde(rename = "exclusion")]
    Exclusion,
    #[serde(rename = "constraint")]
    Constraint,
    #[serde(rename = "uncertainty")]
    Uncertainty,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkingContextProjectionSemanticItemUserReview {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "edited")]
    Edited,
    #[serde(rename = "excluded")]
    Excluded,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrant {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub status: ConsentGrantStatus,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub purposes: Vec<ConsentGrantPurpose>,
    pub actions: Vec<ConsentGrantAction>,
    pub sources: Vec<ConsentGrantSource>,
    pub retention: ConsentGrantRetention,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantRetention {
    pub mode: ConsentGrantRetentionMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_derived_projection: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_personal_model_update: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantSource {
    pub source_id: String,
    pub source_type: ConsentGrantSourceSourceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantV2 {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub status: ConsentGrantV2Status,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub purposes: Vec<ConsentGrantV2Purpose>,
    pub actions: Vec<ConsentGrantV2Action>,
    pub sources: Vec<ConsentGrantV2Source>,
    pub retention: ConsentGrantV2Retention,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantV2Retention {
    pub mode: ConsentGrantV2RetentionMode,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_derived_projection: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_personal_model_update: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConsentGrantV2Source {
    pub source_id: String,
    pub source_type: ConsentGrantV2SourceSourceType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResult {
    pub schema_version: String,
    pub id: String,
    pub generation_spec_id: String,
    pub status: GenerationResultStatus,
    pub adapter: GenerationResultAdapter,
    pub model: GenerationResultModel,
    pub code_revision: String,
    pub device_class: String,
    pub elapsed_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective_parameters: Option<serde_json::Value>,
    pub artifacts: Vec<GenerationResultArtifact>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub feature_report: Option<GenerationResultFeatureReport>,
    pub warnings: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure: Option<GenerationResultFailure>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultAdapter {
    pub id: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultArtifact {
    pub kind: GenerationResultArtifactKind,
    pub path: String,
    pub sha256: String,
    pub media_type: String,
    pub size_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultFailure {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GenerationResultFeatureReport {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tempo_bpm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub loudness_lufs: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_adherence: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub analyzer_versions: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationResultModel {
    pub id: String,
    pub revision: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpec {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub journey_plan_id: String,
    pub journey_plan_hash: String,
    pub adapter: GenerationSpecAdapter,
    pub model: GenerationSpecModel,
    pub duration_seconds: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub negative_prompt: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required_capabilities: Option<Vec<String>>,
    pub output: GenerationSpecOutput,
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecAdapter {
    pub id: String,
    pub version: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecModel {
    pub id: String,
    pub revision: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationSpecOutput {
    pub format: GenerationSpecOutputFormat,
    pub sample_rate_hz: i64,
    pub channels: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelope {
    pub schema_version: String,
    pub package_id: String,
    pub package_kind: H1PublicResultEnvelopePackageKind,
    pub source_record_id: H1PublicResultEnvelopeSourceRecordId,
    pub stage: String,
    pub evidence_class: H1PublicResultEnvelopeEvidenceClass,
    pub source_revision: String,
    pub protocol: H1PublicResultEnvelopeVersionedArtifact,
    pub analysis_plan: H1PublicResultEnvelopeAnalysisPlan,
    pub evidence_set: H1PublicResultEnvelopeEvidenceSet,
    pub complete_accounting: H1PublicResultEnvelopeAggregateAccounting,
    pub public_aggregates: Vec<H1PublicResultEnvelopeNumericSummary>,
    pub artifacts: Vec<H1PublicResultEnvelopePublicArtifact>,
    pub privacy_review: H1PublicResultEnvelopePrivacyReview,
    pub promotion: H1PublicResultEnvelopePromotion,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub assignment_commitment: Option<H1PublicResultEnvelopeAssignmentCommitment>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flow_accounting: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interruptions: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub withdrawals: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failures: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclusions: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub missingness: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instrument_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_accounting: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correction_accounting: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub immediate_windows: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub later_windows: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub analysis_outputs: Option<Vec<H1PublicResultEnvelopeNumericSummary>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub safety_accounting: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mismatches: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unwanted_intensity: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub burden: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub harm: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stops: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub adverse_events: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub review_dispositions: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub package_references: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cross_package_reconciliation: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provenance_linkability: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub deviations: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progression_criteria: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progression_disposition: Option<H1PublicResultEnvelopeProgressionDisposition>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub protocol_amendment: Option<H1PublicResultEnvelopeAmendmentStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub consent_scope: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_manifest: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clock_sync: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signal_quality: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_accounting: Option<H1PublicResultEnvelopeAggregateAccounting>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dropout: Option<H1PublicResultEnvelopeAggregateAccounting>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeAggregateAccounting {
    pub status: H1PublicResultEnvelopeAggregateAccountingStatus,
    pub denominator: i64,
    pub categories: Vec<H1PublicResultEnvelopeCategoryCount>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeAmendmentStatus {
    pub status: H1PublicResultEnvelopeAmendmentStatusStatus,
    pub amendment_id: Option<String>,
    pub sha256: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeAnalysisPlan {
    pub id: String,
    pub version: String,
    pub sha256: String,
    pub deviation_log_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeAssignmentCommitment {
    pub status: H1PublicResultEnvelopeAssignmentCommitmentStatus,
    pub schedule_count: i64,
    pub commitment_sha256: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeCategoryCount {
    pub category: String,
    pub count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeEvidenceSet {
    pub evidence_set_id: String,
    pub commitment_profile: String,
    pub evidence_set_sha256: String,
    pub record_count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeNumericSummary {
    pub metric_id: String,
    pub analysis_id: String,
    pub status: H1PublicResultEnvelopeNumericSummaryStatus,
    pub denominator: i64,
    pub estimate: Option<f64>,
    pub lower: Option<f64>,
    pub upper: Option<f64>,
    pub unit: H1PublicResultEnvelopeNumericSummaryUnit,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopePassedPrivacyReview {
    pub status: String,
    pub scope: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopePhysiologyEvidenceSet {
    pub evidence_set_id: String,
    pub commitment_profile: String,
    pub evidence_set_sha256: String,
    pub record_count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopePrivacyReview {
    pub status: H1PublicResultEnvelopePrivacyReviewStatus,
    pub scope: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopePromotion {
    pub disposition: H1PublicResultEnvelopePromotionDisposition,
    pub claim_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopePublicArtifact {
    pub artifact_id: String,
    pub kind: H1PublicResultEnvelopePublicArtifactKind,
    pub media_type: H1PublicResultEnvelopePublicArtifactMediaType,
    pub sha256: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeReviewEligiblePromotion {
    pub disposition: String,
    pub claim_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeSharedH1EvidenceSet {
    pub evidence_set_id: String,
    pub commitment_profile: String,
    pub evidence_set_sha256: String,
    pub record_count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct H1PublicResultEnvelopeVersionedArtifact {
    pub id: String,
    pub version: String,
    pub sha256: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlan {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub moment_context_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_projection_id: Option<String>,
    pub status: JourneyPlanStatus,
    pub strategy: String,
    pub total_duration_seconds: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supersedes_plan_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rule_set: Option<JourneyPlanRuleSet>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_policy: Option<JourneyPlanControlPolicy>,
    pub stages: Vec<JourneyPlanStage>,
    pub safety_constraints: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub derivations: Option<Vec<JourneyPlanDerivation>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approved_at: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanControlPolicy {
    pub supported_controls: Vec<JourneyPlanControlPolicySupportedControl>,
    pub stagewise_controls: bool,
    pub tempo_bpm_min: f64,
    pub tempo_bpm_max: f64,
    pub density_ceiling: f64,
    pub spatiality_ceiling: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanDerivation {
    pub target: String,
    pub source: JourneyPlanDerivationSource,
    pub rule_id: String,
    pub rationale: String,
    pub uncertainty: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanRuleSet {
    pub id: String,
    pub version: String,
    pub input_hash: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanStage {
    pub id: String,
    pub order: i64,
    pub role: JourneyPlanStageRole,
    pub duration_seconds: i64,
    pub semantic_intent: Vec<String>,
    pub acoustic_controls: JourneyPlanStageAcousticControls,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transition_rationale: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JourneyPlanStageAcousticControls {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tempo_bpm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_signature: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timbre: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub harmony: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub density: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spatiality: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dynamics: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContext {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub observed_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub working_projection_id: Option<String>,
    pub current_state: MomentContextState,
    pub desired_transition: MomentContextDesiredTransition,
    pub time_horizon_seconds: i64,
    pub inclusions: Vec<String>,
    pub exclusions: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContextDesiredTransition {
    pub direction: MomentContextDesiredTransitionDirection,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_state: Option<MomentContextState>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MomentContextState {
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arousal: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PrivateEvidenceIndex {
    pub schema_version: String,
    pub evidence_set_id: String,
    pub commitment_profile: String,
    pub evidence_set_sha256: String,
    pub record_count: i64,
    pub storage_class: String,
    pub domain_separator: String,
    pub canonicalization_profile: String,
    pub record_order: String,
    pub private_nonce: String,
    pub records: Vec<PrivateEvidenceIndexPrivateRecord>,
    pub retention_disposition: PrivateEvidenceIndexRetentionDisposition,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PrivateEvidenceIndexPrivateRecord {
    pub opaque_ref: String,
    pub package_scope: PrivateEvidenceIndexPrivateRecordPackageScope,
    pub payload_schema_id: String,
    pub payload_sha256: String,
    pub accounting_status: PrivateEvidenceIndexPrivateRecordAccountingStatus,
    pub reason: Option<PrivateEvidenceIndexPrivateRecordReason>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservation {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub exposure_id: String,
    pub observed_at: String,
    pub window: ResponseObservationWindow,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instrument_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub perceived_expression: Option<ResponseObservationPerceivedExpression>,
    pub felt_state: Option<ResponseObservationFeltState>,
    pub wanted_intensity: Option<bool>,
    pub helpfulness: Option<f64>,
    pub resonance: Option<f64>,
    pub mismatch: Option<f64>,
    pub harm: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub surprise: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interaction_burden: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_burden: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub missing_fields: Option<Vec<ResponseObservationMissingField>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub missingness_reason: Option<ResponseObservationMissingnessReason>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stopped_early: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub later_aftereffect_requested: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_personal_model_update: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationFeltState {
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arousal: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationPerceivedExpression {
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub valence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arousal: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intensity: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationV2 {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub exposure_id: String,
    pub observed_at: String,
    pub window: ResponseObservationV2Window,
    pub instrument_version: String,
    pub revision: i64,
    pub supersedes_response_id: Option<String>,
    pub correction_reason: Option<String>,
    pub perceived_expression: ResponseObservationV2ResponseState,
    pub felt_state: ResponseObservationV2ResponseState,
    pub wanted_intensity: Option<ResponseObservationV2WantedIntensity>,
    pub helpfulness: Option<f64>,
    pub resonance: Option<f64>,
    pub mismatch: Option<f64>,
    pub harm: Option<f64>,
    pub surprise: Option<f64>,
    pub interaction_burden: Option<f64>,
    pub session_burden: Option<f64>,
    pub ongoing_effect: Option<ResponseObservationV2OngoingEffect>,
    pub aftereffect_meaning: Option<String>,
    pub missingness: Vec<ResponseObservationV2MissingnessEntry>,
    pub stopped_early: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub later_aftereffect_requested: bool,
    pub allow_personal_model_update: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationV2MissingnessEntry {
    pub field: ResponseObservationV2MissingnessEntryField,
    pub reason: ResponseObservationV2MissingnessEntryReason,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ResponseObservationV2ResponseState {
    pub description: Option<String>,
    pub valence: Option<f64>,
    pub arousal: Option<f64>,
    pub intensity: Option<f64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkingContextProjection {
    pub schema_version: String,
    pub id: String,
    pub session_id: String,
    pub consent_grant_ids: Vec<String>,
    pub created_at: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    pub derivation_version: String,
    pub source_event_ids: Vec<String>,
    pub semantic_items: Vec<WorkingContextProjectionSemanticItem>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub projection_hash: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkingContextProjectionSemanticItem {
    pub id: String,
    pub kind: WorkingContextProjectionSemanticItemKind,
    pub text: String,
    pub source_event_ids: Vec<String>,
    pub user_review: WorkingContextProjectionSemanticItemUserReview,
}

pub const CONTRACT_SCHEMAS: &[crate::ContractSchema] = &[
    crate::ContractSchema {
        name: "consent-grant",
        filename: "schemas/consent-grant.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:consent-grant:v1",
        document: include_str!("../../../contracts/schemas/consent-grant.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "consent-grant-v2",
        filename: "schemas/consent-grant.v2.schema.json",
        id: "urn:egohygiene:antidote:schema:consent-grant:v2",
        document: include_str!("../../../contracts/schemas/consent-grant.v2.schema.json"),
    },
    crate::ContractSchema {
        name: "generation-result",
        filename: "schemas/generation-result.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:generation-result:v1",
        document: include_str!("../../../contracts/schemas/generation-result.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "generation-spec",
        filename: "schemas/generation-spec.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:generation-spec:v1",
        document: include_str!("../../../contracts/schemas/generation-spec.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "h1-public-result-envelope",
        filename: "schemas/h1-public-result-envelope.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:h1-public-result-envelope:v1",
        document: include_str!(
            "../../../contracts/schemas/h1-public-result-envelope.v1.schema.json"
        ),
    },
    crate::ContractSchema {
        name: "journey-plan",
        filename: "schemas/journey-plan.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:journey-plan:v1",
        document: include_str!("../../../contracts/schemas/journey-plan.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "moment-context",
        filename: "schemas/moment-context.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:moment-context:v1",
        document: include_str!("../../../contracts/schemas/moment-context.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "private-evidence-index",
        filename: "schemas/private-evidence-index.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:private-evidence-index:v1",
        document: include_str!("../../../contracts/schemas/private-evidence-index.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "response-observation",
        filename: "schemas/response-observation.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:response-observation:v1",
        document: include_str!("../../../contracts/schemas/response-observation.v1.schema.json"),
    },
    crate::ContractSchema {
        name: "response-observation-v2",
        filename: "schemas/response-observation.v2.schema.json",
        id: "urn:egohygiene:antidote:schema:response-observation:v2",
        document: include_str!("../../../contracts/schemas/response-observation.v2.schema.json"),
    },
    crate::ContractSchema {
        name: "working-context-projection",
        filename: "schemas/working-context-projection.v1.schema.json",
        id: "urn:egohygiene:antidote:schema:working-context-projection:v1",
        document: include_str!(
            "../../../contracts/schemas/working-context-projection.v1.schema.json"
        ),
    },
];
